[workspace]
members = ["envman", "envman_derive", "envman_derive_internals", "tests"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.80"
authors = ["Moriyoshi Kasuga <moriyoshi.kasuga1218@gmail.com>"]
license = "MIT"
